const affirmations = [
    "You got this.",
    "I matter and what I have to offer this world also matters.",
    "I love and approve of myself.",
    "I know I can accomplish anything I set my mind to.",
    "Sucking at something is the first step towards being good at something.",
    "I have as much brightness to offer the world as the next person.",
    "Everything has cracks - that's how the light gets in.",
    "Mistakes don't make you less capable.",
    "We are all works in progress.",
    "You are a capable human.",
    "I forgive myself for all the mistakes I have made.",
    "I may be one in 7 billion but I am also one in 7 billion.",
    "If everything was easy you'd be bored.",
    "I refuse to give up because I haven’t tried all possible ways.",
    "You're resourceful and clever.",
    "You'll find a way",
    "I surround myself with people who treat me well.",
    "Struggling means you're learning.",
    "You're doing a great job",
    "I fill my day with hope and face it with joy.",
    "I compare myself only to my highest self.",
    "Your mind is full of brilliant ideas.",
    "You make a difference in the world by simply existing in it.",
    "You are learning valuable lessons from yourself every day.",
    "You are worthy and deserving of respect.",
    "You know more than you knew yesterday.",
    "You're an inspiration.",
    "Your life is already a miracle of chance waiting for you to shape its destiny.",
    "Your life is about to be incredible.",
    "Nothing is impossible. The word itself says 'I’m possible!'",
    "Failure is just another way to learn how to do something right.",
    "I give myself permission to do what is right for me.",
    "You can do it.",
    "It is not a sprint, it is a marathon. One step at a time.",
    "Success is the progressive realization of a worthy goal.",
    "People with goals succeed because they know where they’re going.",
    "All you need is the plan, the roadmap, and the courage to press on to your destination.",
    "The opposite of courage in our society is not cowardice... it is conformity.",
    "Whenever we’re afraid, it’s because we don’t know enough. If we understood enough, we would never be afraid.",
    "The past does not equal the future.",
    "The path to success is to take massive, determined action.",
    "It’s what you practice in private that you will be rewarded for in public.",
    "Small progress is still progress.",
    "Don't worry if you find flaws in your past creations, it's because you've evolved.",
    "Starting is the most difficult step - but you can do it.",
    "Don't forget to enjoy the journey.",
    "It's not a mistake, it's a learning opportunity.",
  ];
  
  module.exports = affirmations